In [1]:
import numpy as np
from functools import cache

In [2]:
file1 = open('input.txt', 'r')
lines = file1.readlines()

In [3]:
input = np.array([list(line.strip()) for line in lines], dtype=str)
input

array([['O', '.', '.', '.', '.', '#', '.', '.', '.', '.'],
       ['O', '.', 'O', 'O', '#', '.', '.', '.', '.', '#'],
       ['.', '.', '.', '.', '.', '#', '#', '.', '.', '.'],
       ['O', 'O', '.', '#', 'O', '.', '.', '.', '.', 'O'],
       ['.', 'O', '.', '.', '.', '.', '.', 'O', '#', '.'],
       ['O', '.', '#', '.', '.', 'O', '.', '#', '.', '#'],
       ['.', '.', 'O', '.', '.', '#', 'O', '.', '.', 'O'],
       ['.', '.', '.', '.', '.', '.', '.', 'O', '.', '.'],
       ['#', '.', '.', '.', '.', '#', '#', '#', '.', '.'],
       ['#', 'O', 'O', '.', '.', '#', '.', '.', '.', '.']], dtype='<U1')

In [3]:
input = np.array([list(line.strip()) for line in lines], dtype=str)

def process_line(line):
    next_space = -1
    for pos in range(len(line)):
        if line[pos] == '.' and next_space == -1:
            next_space = pos
            continue
        if line[pos] == 'O':
            if next_space == -1:
                continue
            line[next_space] = 'O'
            line[pos] = '.'
            next_space += 1
            continue
        if line[pos] == '#':
            next_space = -1
            continue
    return line

for i in range(input.shape[1]):
    input[:,i] = process_line(input[:,i])

sum_v1 = 0
for i, line in enumerate(input):
    current_score = sum(line == 'O') * (input.shape[0] - i)
    sum_v1 += current_score
print(f"part 1: {sum_v1}")

part 1: 109596


In [47]:
input = np.array([list(line.strip()) for line in lines], dtype=str)
nb_cycle = 1000

history = {}

def create_hash(input):
    return ''.join(input.flatten())

nb_loop = 0
for j in range(nb_cycle):
    hash = create_hash(input)

    if nb_loop == 50:
        break

    if hash in history:
        input = history[hash]["data"]
        history[hash]["all"].append(j)
        nb_loop += 1
        continue
    nb_loop = 0
    #north
    for i in range(input.shape[1]):
        input[:,i] = process_line(input[:,i])
    #west
    for i in range(input.shape[0]):
        input[i] = process_line(input[i])

    #south
    for i in range(input.shape[1]):
        input[:,i] = np.flip(process_line(np.flip(input[:,i])))

    #east
    for i in range(input.shape[0]):
        input[i] = np.flip(process_line(np.flip(input[i])))

    history[hash] = {"data": input.copy(), "original": j, "all": []}


sum_v2 = 0
for i, line in enumerate(input):
    current_score = sum(line == 'O') * (input.shape[0] - i)
    sum_v2 += current_score
print(f"part 2: {sum_v2}")
print(input)

part 2: 96093
[['.' '.' '.' ... '.' '.' 'O']
 ['O' '#' '.' ... '.' '.' '.']
 ['.' '.' '.' ... '#' '#' '.']
 ...
 ['.' '.' '.' ... '.' 'O' 'O']
 ['O' 'O' 'O' ... 'O' 'O' 'O']
 ['O' 'O' '#' ... '.' 'O' 'O']]


In [48]:
for i in history.values():
    print(i["original"], i["all"])

0 []
1 []
2 []
3 []
4 []
5 []
6 []
7 []
8 []
9 []
10 []
11 []
12 []
13 []
14 []
15 []
16 []
17 []
18 []
19 []
20 []
21 []
22 []
23 []
24 []
25 []
26 []
27 []
28 []
29 []
30 []
31 []
32 []
33 []
34 []
35 []
36 []
37 []
38 []
39 []
40 []
41 []
42 []
43 []
44 []
45 []
46 []
47 []
48 []
49 []
50 []
51 []
52 []
53 []
54 []
55 []
56 []
57 []
58 []
59 []
60 []
61 []
62 []
63 []
64 []
65 []
66 []
67 []
68 []
69 []
70 []
71 []
72 []
73 []
74 []
75 []
76 []
77 []
78 []
79 []
80 []
81 []
82 []
83 []
84 []
85 []
86 []
87 []
88 []
89 []
90 []
91 []
92 []
93 []
94 []
95 []
96 [107, 118, 129, 140, 151]
97 [108, 119, 130, 141, 152]
98 [109, 120, 131, 142, 153]
99 [110, 121, 132, 143, 154]
100 [111, 122, 133, 144, 155]
101 [112, 123, 134, 145, 156]
102 [113, 124, 135, 146]
103 [114, 125, 136, 147]
104 [115, 126, 137, 148]
105 [116, 127, 138, 149]
106 [117, 128, 139, 150]


In [49]:
start = min([i["original"] for i in list(filter(lambda x: x["all"], history.values()))])
loop = len(list(filter(lambda x: x["all"], history.values())))

In [50]:
[i["original"] for i in list(filter(lambda x: x["all"], history.values()))]

[96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106]

In [52]:
print(f"start: {start}, loop: {loop}")

start: 96, loop: 11


In [56]:
(1000000000 - (start )) % loop + start

98

In [63]:
cache = list(filter(lambda x: x["original"] == 98, history.values()))[0]["data"]

In [64]:
sum_v2 = 0
for i, line in enumerate(cache):
    current_score = sum(line == 'O') * (cache.shape[0] - i)
    sum_v2 += current_score
print(f"part 2: {sum_v2}")

part 2: 96094


In [100]:
input = np.array([list(line.strip()) for line in lines], dtype=str)
nb_cycle = 1000000000

@cache
def process_line_v2(line):
    line = np.array(line)
    next_space = -1
    for pos in range(len(line)):
        if line[pos] == '.' and next_space == -1:
            next_space = pos
            continue
        if line[pos] == 'O':
            if next_space == -1:
                continue
            line[next_space] = 'O'
            line[pos] = '.'
            next_space += 1
            continue
        if line[pos] == '#':
            next_space = -1
            continue
    return line


@cache
def rotate(vec, x, y):
    return_input = np.reshape(vec, (x, y))
    #north
    for i in range(return_input.shape[1]):
        return_input[:,i] = process_line_v2(tuple(return_input[:,i]))
    #west
    for i in range(return_input.shape[0]):
        return_input[i] = process_line_v2(tuple(return_input[i]))

    #south
    for i in range(return_input.shape[1]):
        return_input[:,i] = np.flip(process_line_v2(tuple(np.flip(return_input[:,i]))))

    #east
    for i in range(return_input.shape[0]):
        return_input[i] = np.flip(process_line_v2(tuple(np.flip(return_input[i]))))
    return return_input

for i in range(nb_cycle):
    input = rotate(tuple(np.reshape(input, (input.shape[0] * input.shape[1]))), input.shape[0], input.shape[1])


print(input)
sum_v2 = 0
for i, line in enumerate(input):
    current_score = sum(line == 'O') * (input.shape[0] - i)
    sum_v2 += current_score
print(f"part 2: {sum_v2}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(1, 2, 3, 4, 5, 6, 7, 8, 9)
inside
111111111
[[1 2 3]
 [4 5 6]
 [7 8 9]]
111111111
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [72]:
import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)